# Generated by Django 3.0.6 on 2020-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='applicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='coapplicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='credithistory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loanamt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loanterm',
            field=models.IntegerField(default=0),
        ),
    ]
